import './global.css';
import Navbar from '@/components/layouts/navbar';
import Footer from '@/components/layouts/footer';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-pattern bg-repeat bg-fixed">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
